version: '3.7'
services:
  web:
    image: docker-create-react-app-image
    container_name: docker-create-react-app
    volumes:
      - .:/app
    build: .
    ports:
      - 3000:3000
    stdin_open: true